"""empty message

Revision ID: 97f16a756ab9
Revises: 14a81bd685f3
Create Date: 2020-04-05 22:25:05.154104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f16a756ab9'
down_revision = '14a81bd685f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE todos SET completed=FALSE WHERE completed is NULL')
    op.alter_column('todos','completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
