"""empty message

Revision ID: 3923258de3ce
Revises: 6d8a48426aec
Create Date: 2020-04-09 05:41:01.422217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3923258de3ce'
down_revision = '6d8a48426aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE todolists SET completed=FALSE WHERE completed is NULL')
    op.alter_column('todolists','completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'completed')
    # ### end Alembic commands ###
